<script setup lang="ts">
import { ref, onMounted } from 'vue';
import * as api from '../services/api';

defineProps<{
  show: boolean;
}>();

const emit = defineEmits<{
  accepted: [];
}>();

const agreementText = ref('');
const scrolledToBottom = ref(false);
const agreementVersion = '1.0';

const scrollContainer = ref<HTMLElement | null>(null);

onMounted(async () => {
  agreementText.value = `# indiBudget User Agreement

**Version 1.0 — Effective June 2026**

This is a legal agreement between you (the "User") and Indomitus Group ("Company"), developed by Matt Milano. By using the indiBudget application as distributed by Indomitus Group, you agree to these terms. This agreement applies to the distributed application only — the indiBudget source code is licensed separately under the MIT License (see Section 2).

---

## In Plain English

indiBudget is free, open-source personal finance software. You can use it without payment or registration. However, the software is provided "as-is" — we do our best to make it great, but we can't guarantee it's perfect or accept responsibility if something goes wrong. This is financial software, so please always verify calculations independently and keep backups of your data.

---

## 1. What You Can Do

- Use indiBudget for personal financial tracking
- Track accounts, transactions, budgets, and goals
- Import and export your financial data
- Use all features without payment or time limits
- Modify the source code under the MIT License

### You May Not:

- Hold Indomitus Group or Matt Milano liable for financial decisions made using this software
- Rely on this software as your sole source of financial record-keeping without independent verification
- Use the software for illegal purposes

---

## 2. Open Source License

The source code of indiBudget is released under the MIT License. This User Agreement governs your use of the compiled application and does not restrict your rights under the MIT License to use, modify, or distribute the source code.

---

## 3. No Warranty (The "As-Is" Part)

**indiBudget is provided "AS IS" without any warranty of any kind.**

We don't guarantee that:
- The software will work perfectly or without interruption
- The software will meet all your specific needs
- Any errors or bugs will be fixed
- The software won't cause issues with your files or system
- Financial calculations, balances, or reports will be accurate in all circumstances

**You are solely responsible for verifying the accuracy of all financial data and reports generated by this software.** indiBudget is a tool to assist with personal finance tracking — it is not a substitute for professional financial advice. Always keep independent backups of your financial data and verify important calculations against your bank statements.

---

## 4. Limitation of Liability

**To the maximum extent permitted by law:**

Indomitus Group and Matt Milano shall not be liable for any damages whatsoever, including but not limited to:
- Lost data or corrupted files
- Inaccurate financial calculations, balances, or reports
- Lost money or missed financial opportunities
- Any indirect, incidental, special, or consequential damages
- Any claims by third parties

This applies whether the claim is based on warranty, contract, negligence, or any other legal theory, even if we were advised of the possibility of such damages.

**Our maximum liability, if any, is limited to zero dollars ($0), as this is free software.**

---

## 5. Indemnification

You agree to defend, indemnify, and hold harmless Indomitus Group and Matt Milano from any claims, damages, losses, or expenses (including legal fees) arising from:
- Your use of indiBudget
- Your violation of this agreement
- Any financial decisions made using data from indiBudget
- Any reliance on calculations, balances, or reports generated by indiBudget

---

## 6. Data Privacy

indiBudget is designed with privacy in mind:
- All your financial data is stored locally on your device
- No data is transmitted to Indomitus Group or any third party
- Optional bank sync via SimpleFIN is between you and SimpleFIN — your credentials never touch indiBudget

You are responsible for securing your device and any backups of your data.

---

## 7. Updates and Changes

We may update indiBudget and this agreement from time to time. Continued use of the software after changes means you accept the new terms. Significant changes to this agreement will prompt you to re-accept the terms.

---

## 8. Termination

You may stop using indiBudget at any time. This agreement remains in effect for the period during which you used the software, including any liability limitations and indemnification provisions.

---

## 9. Governing Law

This agreement is governed by the laws of the jurisdiction where Indomitus Group is registered, without regard to conflict of law principles.

---

## 10. Contact

For questions about this agreement:
- Website: https://www.indibudget.app
- Company: https://www.indomitusgroup.com
- Email: info@indomitusgroup.com
- Source Code: https://github.com/mattmilano/indiBudget

---

**© 2026 Indomitus Group. All rights reserved.**

indiBudget is a trademark of Indomitus Group.`;
});

function handleScroll() {
  if (!scrollContainer.value) return;
  const { scrollTop, scrollHeight, clientHeight } = scrollContainer.value;
  if (scrollTop + clientHeight >= scrollHeight - 20) {
    scrolledToBottom.value = true;
  }
}

async function acceptAgreement() {
  const now = new Date().toISOString();
  await api.setSetting('user_agreement_accepted', 'true');
  await api.setSetting('user_agreement_version', agreementVersion);
  await api.setSetting('user_agreement_accepted_at', now);
  emit('accepted');
}

function declineAgreement() {
  window.close();
}
</script>

<template>
  <div v-if="show" class="fixed inset-0 z-[100] flex items-center justify-center bg-black/60">
    <div class="bg-white dark:bg-gray-800 rounded-xl shadow-2xl w-full max-w-3xl max-h-[90vh] flex flex-col mx-4">
      <!-- Header -->
      <div class="px-6 py-4 border-b border-gray-200 dark:border-gray-700">
        <h2 class="text-xl font-bold text-gray-900 dark:text-white">User Agreement</h2>
        <p class="text-sm text-gray-600 dark:text-gray-400 mt-1">
          Please read and accept the following agreement to continue using indiBudget.
        </p>
      </div>

      <!-- Agreement Content -->
      <div
        ref="scrollContainer"
        @scroll="handleScroll"
        class="flex-1 overflow-y-auto px-6 py-4 prose prose-sm dark:prose-invert max-w-none"
      >
        <div class="whitespace-pre-wrap text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
          {{ agreementText }}
        </div>
      </div>

      <!-- Scroll indicator -->
      <div v-if="!scrolledToBottom" class="px-6 py-2 bg-amber-50 dark:bg-amber-900/30 border-t border-amber-200 dark:border-amber-800">
        <p class="text-sm text-amber-700 dark:text-amber-400 text-center">
          Please scroll to read the entire agreement
        </p>
      </div>

      <!-- Footer -->
      <div class="px-6 py-4 border-t border-gray-200 dark:border-gray-700 flex justify-end gap-3">
        <button
          @click="declineAgreement"
          class="px-4 py-2 text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors"
        >
          Decline & Exit
        </button>
        <button
          @click="acceptAgreement"
          :disabled="!scrolledToBottom"
          :class="[
            'px-6 py-2 rounded-lg font-medium transition-colors',
            scrolledToBottom
              ? 'bg-blue-600 text-white hover:bg-blue-700'
              : 'bg-gray-300 dark:bg-gray-600 text-gray-500 dark:text-gray-400 cursor-not-allowed'
          ]"
        >
          I Agree
        </button>
      </div>
    </div>
  </div>
</template>
